### ISSUE TITLE
[Character Name Database] Create personal cast lists

### ISSUE THREAD

**Issue by harp37** [lmparppei/BeatPlugins#3]
I'd love to favorite names or, even better, create personal "cast lists" for different projects. Just a suggestion, not Earth-shattering or anything. I know that'll definitely add some complexity to the plugin, thereby adding a greater probability for things to break in the future. But I do think it'd be pretty useful for brainstorming characters at the very least. The ability to label or add brief notes to the characters in the cast list would be also pretty useful.

**Comment by lmparppei** [comment]
This is a job for somebody else than me. You can save an array of favorites/starred items/any other data using `Beat.setUserDefault()`. Communicating from the HTML panel might be a bit tricky, though, but still doable.

First get the list (`const names = Beat.getUserDefaut("favorites")`) then inject that data into the HTML with `JSON.stringify()`. In the HTML side, store any changes to the user-made item and pass them back using the `Beat.data` object. Then, before terminating the plugin, save the new stuff into the user defaults.

**Comment by lmparppei** [comment]
With `Beat.call()` available in both `htmlPanel` and `htmlWindow`, this should be much easier to implement. The whole of Character Name Database should probably be moved into a `htmlWindow`.
